### ISSUE TITLE
Refactor lodestar code to separate out web application and configuration info

### ISSUE THREAD

**Issue by Klortho** [HHS/lodestar#12]
Right now, NLM MeSH RDF project is using a permanent fork of the lodestar repository, in the `meshrdf` branch, here: [https://github.com/hhs/lodestar/tree/meshrdf](https://github.com/hhs/lodestar/tree/meshrdf).

Ideally, we wouldn't need a complete fork of the whole lodestar repository, because we are just changing various configuration settings and the sparql query page, for example (complete report of the differences is [here](https://github.com/HHS/lodestar/compare/meshrdf)). Simon showed me the [ensemble-rdf lodestar-ui repository](https://github.com/simonjupp/ensembl-rdf/tree/master/lodestar-ui), which should be pretty close to what we'd want. But for now, having a complete fork of lodestar is simplest.

We need to separate out our web application, which is currently just the `web-ui` module, of the application, and then just import the EBI lodestar jars (which will hopefully be on a public Maven repository somewhere) during the build.

**Comment by danizen** [comment]
@Klortho , do you plan on doing this soon?    I've added to meshrdf-danizen branch a script ./build-to-war.sh that is used from configscripts-danizen to build the war in one command from the Makefile there.

**Comment by Klortho** [comment]
No, I'm afraid not.  This is more of a "maybe/someday" issue -- I wanted to record the info about what needed to be done, but I really don't have time now to do it. I had talked this over with @simonjupp, and he seemed to concur.

**Comment by Klortho** [comment]
By him concurring, I meant, of course, that he concurs with this approach -- not that I don't have time to do it now.  :)

**Comment by danizen** [comment]
This is closed.
